{{- if .Values.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-manager.fullname" . }}-ssh
  labels:
    app: {{ include "scm-manager.name" . }}
    chart: {{ include "scm-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - port: {{ .Values.ssh.service.port }}
      targetPort: {{ .Values.ssh.port }}
      protocol: TCP
      name: ssh
  selector:
    app: {{ include "scm-manager.name" . }}
    release: {{ .Release.Name }}
{{- end }}